Traceback (most recent call last):
  File "/Users/wjohal/opt/anaconda3/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/wjohal/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/wjohal/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/wjohal/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/wjohal/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/wjohal/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/wjohal/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/wjohal/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------

cv_image = image
ros, cols , channels = cv_image.shape
cv2.circle(cv_image, (cols/2,ros/2), 50, (0,0,255), -1)
image_pub.publish(bridge.cv2_to_imgmsg(cv_image,"brg8"))

rospy.init_node('image_processing')
bridge = CvBridge()
image_pub = rospy.Publisher("processed_image", Image)

while not rospy.is_shutdown():
    rospy.spin()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Input [0;32mIn [3][0m, in [0;36m<cell line: 1>[0;34m()[0m
[0;32m----> 1[0m cv_image [38;5;241m=[39m [43mimage[49m
[1;32m      2[0m ros, cols , channels [38;5;241m=[39m cv_image[38;5;241m.[39mshape
[1;32m      3[0m cv2[38;5;241m.[39mcircle(cv_image, (cols[38;5;241m/[39m[38;5;241m2[39m,ros[38;5;241m/[39m[38;5;241m2[39m), [38;5;241m50[39m, ([38;5;241m0[39m,[38;5;241m0[39m,[38;5;241m255[39m), [38;5;241m-[39m[38;5;241m1[39m)

[0;31mNameError[0m: name 'image' is not defined
NameError: name 'image' is not defined

